#!/usr/bin/env python3
"""Expand shared GLSL into standalone KodeLife passes and the browser bundle."""
from pathlib import Path
import json
import sys
root=Path(__file__).resolve().parents[1]
common=(root/'src/common.glsl').read_text()
outputs={}
for p in sorted((root/'src').glob('[0-9]*.glsl')):
    outputs[p.stem]='#version 150\n'+common+'\n'+p.read_text()
files={root/'shaders'/f'{name}.frag':code for name,code in outputs.items()}
files[root/'demo/shaders.js']='// Generated by tools/build.py; edit src/*.glsl instead.\nwindow.FLUID_SHADERS = '+json.dumps(outputs,ensure_ascii=False,indent=2)+';\n'
for p,content in files.items():
    if '--check' in sys.argv:
        if not p.exists() or p.read_text()!=content:
            raise SystemExit('Stale generated file: '+str(p))
    else:
        p.parent.mkdir(parents=True,exist_ok=True)
        p.write_text(content)
print(f'{len(files)} generated files '+('verified' if '--check' in sys.argv else 'written'))

# Also ship a single file that opens without npm, a server, or a network connection.
preview=(root/'demo/index.html').read_text().replace('<script src="shaders.js"></script>',
    '<script>'+files[root/'demo/shaders.js']+'</script>').replace('<script src="app.js"></script>',
    '<script>'+(root/'demo/app.js').read_text()+'</script>')
p=root/'preview.html'
if '--check' in sys.argv:
    if not p.exists() or p.read_text()!=preview: raise SystemExit('Stale preview.html')
else: p.write_text(preview)

passes=[]
def add(name,shader,inputs=None,size=(512,512)):
    passes.append(dict(name=name,shader='shaders/'+shader+'.frag',resolution=list(size),
                       format='RGBA32F',inputs=inputs or {}))
add('Clock','00_clock',{'clockTex':{'pass':'Clock','frame':'previous'}},(1,1))
add('Advect','01_advect_velocity',{'stateTex':{'pass':'State','frame':'previous'}})
add('Curl','02_curl',{'velocityTex':{'pass':'Advect','frame':'current'}})
add('Forces','03_forces',{'velocityTex':{'pass':'Advect','frame':'current'},'curlTex':{'pass':'Curl','frame':'current'},'clockTex':{'pass':'Clock','frame':'current'}})
add('Divergence','04_divergence',{'velocityTex':{'pass':'Forces','frame':'current'}})
add('PressureSeed','05_pressure_seed')
for i in range(1,41):
    add(f'P{i:02}','06_pressure_jacobi',{'pressureTex':{'pass':'PressureSeed' if i==1 else f'P{i-1:02}','frame':'current'},'divergenceTex':{'pass':'Divergence','frame':'current'}})
add('Project','07_project',{'velocityTex':{'pass':'Forces','frame':'current'},'pressureTex':{'pass':'P40','frame':'current'}})
add('DensityForward','08_density_forward',{'velocityTex':{'pass':'Project','frame':'current'},'stateTex':{'pass':'State','frame':'previous'}})
add('DensityReverse','09_density_reverse',{'velocityTex':{'pass':'Project','frame':'current'},'forwardTex':{'pass':'DensityForward','frame':'current'}})
add('State','10_state',{'stateTex':{'pass':'State','frame':'previous'},'velocityTex':{'pass':'Project','frame':'current'},'forwardTex':{'pass':'DensityForward','frame':'current'},'reverseTex':{'pass':'DensityReverse','frame':'current'},'clockTex':{'pass':'Clock','frame':'current'}})
add('Render','11_render',{'stateTex':{'pass':'State','frame':'current'}},(720,540))
manifest={'description':'Wiring reference, not a native KodeLife project file','grid':64,'columns':8,'pressureIterations':40,
 'parameters':{'gridSize':64,'dt':1/60,'reset':0,'mode':0,'confinement':2,'yaw':0.35,'pitch':0.08,'absorption':32,'debugView':0},'passes':passes}
content=json.dumps(manifest,ensure_ascii=False,indent=2)+'\n'
p=root/'pipeline.json'
if '--check' in sys.argv:
    if not p.exists() or p.read_text()!=content: raise SystemExit('Stale pipeline.json')
else: p.write_text(content)
print('Standalone preview and 51-pass wiring reference '+('verified' if '--check' in sys.argv else 'written'))
